### ISSUE TITLE
TypeError: first argument must be callable or None

### ISSUE THREAD

**Issue by TianleLiu0303** [Div99/IQ-Learn#20]
Traceback (most recent call last):
  File "train_iq.py", line 44, in main
    wandb.init(project=args.project_name, entity='iq-learn',
  File "/home/ltl/anaconda3/envs/iq_learn/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1312, in init
    wandb._sentry.reraise(e)
  File "/home/ltl/anaconda3/envs/iq_learn/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 156, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/ltl/anaconda3/envs/iq_learn/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1298, in init
    return wi.init()
  File "/home/ltl/anaconda3/envs/iq_learn/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 700, in init
    run = Run(
  File "/home/ltl/anaconda3/envs/iq_learn/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 577, in __init__
    self._init(
  File "/home/ltl/anaconda3/envs/iq_learn/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 682, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/ltl/anaconda3/envs/iq_learn/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 180, in _update
    sanitized = self._sanitize_dict(
  File "/home/ltl/anaconda3/envs/iq_learn/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 267, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/ltl/anaconda3/envs/iq_learn/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 285, in _sanitize
    val = json_friendly_val(val)
  File "/home/ltl/anaconda3/envs/iq_learn/lib/python3.8/site-packages/wandb/util.py", line 646, in json_friendly_val
    converted = asdict(val)
  File "/home/ltl/anaconda3/envs/iq_learn/lib/python3.8/dataclasses.py", line 1073, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/home/ltl/anaconda3/envs/iq_learn/lib/python3.8/dataclasses.py", line 1080, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/home/ltl/anaconda3/envs/iq_learn/lib/python3.8/dataclasses.py", line 1110, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: first argument must be callable or None

**Comment by mirajull** [comment]
wandb.init(project=args.project_name, entity='iq-learn', sync_tensorboard=True, reinit=True, config=OmegaConf.to_container(args, resolve=True))

And also make sure you have wandb project and entity as named.
